CREATE DATABASE IF NOT EXISTS portfoliodb;

USE portfoliodb;

DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS underconstruction;
DROP TABLE IF EXISTS pmessages;
DROP TABLE IF EXISTS phone;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS register;
DROP TABLE IF EXISTS cvs;
DROP TABLE IF EXISTS schools;
DROP TABLE IF EXISTS trainings;
DROP TABLE IF EXISTS hobbies;
DROP TABLE IF EXISTS profiles;

CREATE TABLE projects (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, projecttitle VARCHAR(255) NOT NULL, projectdescription VARCHAR(255) NOT NULL,videolink VARCHAR(255) NOT NULL, githubname VARCHAR(255) NOT NULL,projectlink VARCHAR(255) NOT NULL); 
CREATE TABLE skills (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,skill VARCHAR(255) NOT NULL); 
CREATE TABLE underconstruction (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, underconstruction boolean NOT NULL);
INSERT INTO  underconstruction (underconstruction)values(false); 
CREATE TABLE pmessages (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, pmessage VARCHAR(255) NOT NULL); 
CREATE TABLE phone (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, phone VARCHAR(255) NOT NULL,myemail VARCHAR(255) NOT NULL,linkedin VARCHAR(255) NOT NULL,instagramname VARCHAR(255) NOT NULL); 
CREATE TABLE photos (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, photo VARCHAR(255) NOT NULL); 
CREATE TABLE messages (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, companyname VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL); 
CREATE TABLE register (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, name  VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, maidenname  VARCHAR(255) NOT NULL,password  VARCHAR(255) NOT NULL); 
CREATE TABLE cvs (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, cv VARCHAR(255) NOT NULL); 
CREATE TABLE schools (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, honor VARCHAR(255) NOT NULL,school  VARCHAR(255), course  VARCHAR(255) NOT NULL, courselink  VARCHAR(255) NOT NULL, graduationyear VARCHAR(255) NOT NULL); 
CREATE TABLE trainings (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, course  VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL,companywebsite  VARCHAR(255) NOT NULL,certificate  VARCHAR(255) NOT NULL, year  INT(6) NOT NULL); 
CREATE TABLE hobbies (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, hobby VARCHAR(255) NOT NULL); 
CREATE TABLE profiles (id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, profiletitle VARCHAR(255) NOT NULL, profile VARCHAR(255) NOT NULL); 

